version: '3.8'

services:

  product-db:
    image: mysql:latest
    container_name: product-db
    environment:
      MYSQL_DATABASE: product-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - product-network

volumes:
  mysql_data:

networks:
  product-network:
    driver: bridge