name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permitir execução do Maven Wrapper
        run: chmod +x mvnw

      - name: Buildar o projeto com perfil prod
        run: ./mvnw clean package -Pprod

      - name: Gerar imagem Docker
        run: docker build -t product-api .
